services:
  valheim:
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes:
      - ./config:/config
      - ./data:/opt/valheim
    ports:
      - "2456-2458:2456-2458/udp"
      - "9001:9001/tcp"
    env_file:
      - ./valheim.env
    restart: always
    stop_grace_period: 2m
    networks:
      - valheim
  valheim-status:
    build: ./status
    working_dir: /app
    volumes:
      - ./status:/app
      - ./:/opt/valheim
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - ${NODE_PORT:-3529}:${NODE_PORT:-3529}
    privileged: true
    command: ["node", "index.js"]
    restart: always
    networks:
      - valheim

networks:
  valheim:
